services:
  yukon-energy:
    build: .
    restart: always
    container_name: yukon-energy_server
    pull_policy: build
    environment:
      - FLASK_ENV=development
    networks:
      - reverse_proxy
    volumes:
      - yukon-energy-data:/app
      
volumes:
  yukon-energy-data: {}

networks:
  reverse_proxy:
    external: true
