services:
  yukon-energy:
    build: .
    restart: always
    container_name: yukon-energy_server
    pull_policy: build
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external: true
