CREATE TABLE DATA (
    id INTEGER PRIMARY KEY, 
    timestamp TIMESTAMP UNIQUE NOT NULL, 
    hydro REAL DEFAULT 0, 
    thermal REAL DEFAULT 0,
    wind REAL DEFAULT 0,
    solar REAL DEFAULT 0
    );
